name: Main

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Lint
      run: make lint
