name: Local run

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'

jobs:
  local-run:
    strategy:
      matrix:
        scheme: ["http", "https"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Locally run oval with MinIO
      env:
        AWS_ACCESS_KEY_ID: "minioadmin"
        AWS_SECRET_ACCESS_KEY: "minioadmin"
        AWS_DEFAULT_REGION: "jp-tokyo-test"
      run: |
        S3_ENDPOINT="${{ matrix.scheme }}://localhost:9000"
        CERT_CONFIG=""
        if [ "${{ matrix.scheme }}" == "https" ]; then
          CERT_CONFIG="--cacert=test/certs/public.crt"
          make start-minio-https
        else
          make start-minio
        fi
        make run S3_ENDPOINT=${S3_ENDPOINT} CERT_CONFIG=${CERT_CONFIG}
        make run-multi-process S3_ENDPOINT=${S3_ENDPOINT} CERT_CONFIG=${CERT_CONFIG}
        make run-leader-with-config S3_ENDPOINT=${S3_ENDPOINT} CERT_CONFIG=${CERT_CONFIG}
        make stop-minio
