name: Local run

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Locally run oval with MinIO
      env:
        AWS_ACCESS_KEY_ID: "minioadmin"
        AWS_SECRET_ACCESS_KEY: "minioadmin"
      run: make local-run
